version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9001" http://minio-node0{1...3}/data{1...4}
  expose:
    - "9000"
    - "9001"
  network_mode: "host"  
  
  environment:
    MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
    MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASS:-minioadmin}
    MINIO_REGION_NAME: ${MINIO_REGION_NAME}
    MINIO_BROWSER_REDIRECT_URL: https://${FQDN}
    MINIO_PROMETHEUS_URL: ${MINIO_PROMETHEUS_URL}  
  
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio:
    <<: *minio-common
    hostname: minio
    volumes:
      - /mnt/disk1/minio:/data1
      - /mnt/disk2/minio:/data2
      - /mnt/disk3/minio:/data3
      - /mnt/disk4/minio:/data4

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/certs
    ports:
      - "443:443"
      - "15443:15443"
    depends_on:
      - minio
      
  prometheus:
    image: prom/prometheus:latest
    expose:
      - "9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=48h
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: on-failure

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  prometheus_data:
