version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9001" http://minio-node0{1...3}/data{1...4}
  expose:
    - "9000"
    - "9001"

  secrets:
    - secret_key
    - access_key

  environment:
    MINIO_BROWSER_REDIRECT_URL: "https://s3.c4a.free.ci"
    MINIO_PROMETHEUS_URL: "http://prometheus:9090" 
    
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  minio-node01:
    <<: *minio-common
    hostname: minio-node01
    volumes:
      - /mnt/disk1/minio:/data1
      - /mnt/disk2/minio:/data2
      - /mnt/disk3/minio:/data3
      - /mnt/disk4/minio:/data4
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:  
        constraints:
          - node.labels.minio-node01==true

  minio-node02:
    <<: *minio-common
    hostname: minio-node02
    volumes:
      - /mnt/disk1/minio:/data1
      - /mnt/disk2/minio:/data2
      - /mnt/disk3/minio:/data3
      - /mnt/disk4/minio:/data4
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:  
        constraints:
          - node.labels.minio-node02==true

  minio-node03:
    <<: *minio-common
    hostname: minio-node03
    volumes:
      - /mnt/disk1/minio:/data1
      - /mnt/disk2/minio:/data2
      - /mnt/disk3/minio:/data3
      - /mnt/disk4/minio:/data4
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      placement:  
        constraints:
          - node.labels.minio-node03==true
      
            
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/certs
    ports:
      - "443:443"
      - "15443:15443"
    depends_on:
      - minio1
      - minio2
      - minio3
      
  prometheus:
    image: prom/prometheus:latest
    expose:
      - "9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=48h
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    restart: on-failure
    depends_on:
      - minio1
      - minio2
      - minio3

## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  prometheus_data:

secrets:
  secret_key:
    external: true
  access_key:
    external: true
